version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      production-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
    cooldown:
      default: 3
      semver-major: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      ci-dependencies:
        applies-to: "version-updates"
        patterns:
          - "*"
    cooldown:
      default: 3
      semver-major: 7
