name: Build notes
on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        name: checkout 🛎️
        with:
          fetch-depth: 0
          submodules: false

      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: Install Dependencies
        run: npm ci

      - name: Check types and style
        run: npm run check

      - name: Test
        run: npm run test

      - name: Ensure Quartz builds, check bundle info
        run: npx quartz build --bundleInfo -d docs
