name: Build notes
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        name: checkout 🛎️
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 18.14
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
