name: Build and publish notes
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        name: checkout 🛎️
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build -d content/garden
        env:
          ANALYTICS_PROVIDER: ${{ vars.ANALYTICS_PROVIDER }}
          ANALYTICS_WEBSITE_ID: ${{ vars.ANALYTICS_WEBSITE_ID }}
          ANALYTICS_HOST: ${{ vars.ANALYTICS_HOST }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
